applications:
- api_domain: api.dev.jitdev.io
  application_name: PlatformDev1687704207597
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://platform.dev.jitdev.io
  type: web
